version: '{build}'
skip_tags: true
clone_depth: 10
init:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
install:
  - cmd: SET MAVEN_OPTS=-Xmx4g
  - cmd: SET JAVA_OPTS=-Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -Dmaven.test.skip=true
test_script:
  - mvn clean install --batch-mode -Pqulice
artifacts:
- path: target/PreventGriefing.jar
  name: PreventGriefing
